// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-dashboard/internal/db/models"
	"go.lumeweb.com/queryutil"
)

// NewMockAPIKeyService creates a new instance of MockAPIKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyService {
	mock := &MockAPIKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyService is an autogenerated mock type for the APIKeyService type
type MockAPIKeyService struct {
	mock.Mock
}

type MockAPIKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyService) EXPECT() *MockAPIKeyService_Expecter {
	return &MockAPIKeyService_Expecter{mock: &_m.Mock}
}

// CreateAPIKey provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) CreateAPIKey(userID uint, name string) (*models.APIKey, error) {
	ret := _mock.Called(userID, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIKey")
	}

	var r0 *models.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) (*models.APIKey, error)); ok {
		return returnFunc(userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string) *models.APIKey); ok {
		r0 = returnFunc(userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = returnFunc(userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyService_CreateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIKey'
type MockAPIKeyService_CreateAPIKey_Call struct {
	*mock.Call
}

// CreateAPIKey is a helper method to define mock.On call
//   - userID uint
//   - name string
func (_e *MockAPIKeyService_Expecter) CreateAPIKey(userID interface{}, name interface{}) *MockAPIKeyService_CreateAPIKey_Call {
	return &MockAPIKeyService_CreateAPIKey_Call{Call: _e.mock.On("CreateAPIKey", userID, name)}
}

func (_c *MockAPIKeyService_CreateAPIKey_Call) Run(run func(userID uint, name string)) *MockAPIKeyService_CreateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_CreateAPIKey_Call) Return(aPIKey *models.APIKey, err error) *MockAPIKeyService_CreateAPIKey_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyService_CreateAPIKey_Call) RunAndReturn(run func(userID uint, name string) (*models.APIKey, error)) *MockAPIKeyService_CreateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAPIKey provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) DeleteAPIKey(userID uint, uuid1 uuid.UUID) error {
	ret := _mock.Called(userID, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAPIKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uuid.UUID) error); ok {
		r0 = returnFunc(userID, uuid1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyService_DeleteAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAPIKey'
type MockAPIKeyService_DeleteAPIKey_Call struct {
	*mock.Call
}

// DeleteAPIKey is a helper method to define mock.On call
//   - userID uint
//   - uuid1 uuid.UUID
func (_e *MockAPIKeyService_Expecter) DeleteAPIKey(userID interface{}, uuid1 interface{}) *MockAPIKeyService_DeleteAPIKey_Call {
	return &MockAPIKeyService_DeleteAPIKey_Call{Call: _e.mock.On("DeleteAPIKey", userID, uuid1)}
}

func (_c *MockAPIKeyService_DeleteAPIKey_Call) Run(run func(userID uint, uuid1 uuid.UUID)) *MockAPIKeyService_DeleteAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_DeleteAPIKey_Call) Return(err error) *MockAPIKeyService_DeleteAPIKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyService_DeleteAPIKey_Call) RunAndReturn(run func(userID uint, uuid1 uuid.UUID) error) *MockAPIKeyService_DeleteAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIKeys provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) GetAPIKeys(userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.APIKey, int64, error) {
	ret := _mock.Called(userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetAPIKeys")
	}

	var r0 []*models.APIKey
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*models.APIKey, int64, error)); ok {
		return returnFunc(userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*models.APIKey); ok {
		r0 = returnFunc(userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIKeyService_GetAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIKeys'
type MockAPIKeyService_GetAPIKeys_Call struct {
	*mock.Call
}

// GetAPIKeys is a helper method to define mock.On call
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockAPIKeyService_Expecter) GetAPIKeys(userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockAPIKeyService_GetAPIKeys_Call {
	return &MockAPIKeyService_GetAPIKeys_Call{Call: _e.mock.On("GetAPIKeys", userID, filters, sorts, pagination)}
}

func (_c *MockAPIKeyService_GetAPIKeys_Call) Run(run func(userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockAPIKeyService_GetAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []queryutil.Sort
		if args[2] != nil {
			arg2 = args[2].([]queryutil.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_GetAPIKeys_Call) Return(aPIKeys []*models.APIKey, n int64, err error) *MockAPIKeyService_GetAPIKeys_Call {
	_c.Call.Return(aPIKeys, n, err)
	return _c
}

func (_c *MockAPIKeyService_GetAPIKeys_Call) RunAndReturn(run func(userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*models.APIKey, int64, error)) *MockAPIKeyService_GetAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPIKeyService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAPIKeyService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAPIKeyService_Expecter) ID() *MockAPIKeyService_ID_Call {
	return &MockAPIKeyService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAPIKeyService_ID_Call) Run(run func()) *MockAPIKeyService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIKeyService_ID_Call) Return(s string) *MockAPIKeyService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPIKeyService_ID_Call) RunAndReturn(run func() string) *MockAPIKeyService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAPIKey provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) ValidateAPIKey(userID uint, keyUUID uuid.UUID) (*models.APIKey, error) {
	ret := _mock.Called(userID, keyUUID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAPIKey")
	}

	var r0 *models.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uuid.UUID) (*models.APIKey, error)); ok {
		return returnFunc(userID, keyUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uuid.UUID) *models.APIKey); ok {
		r0 = returnFunc(userID, keyUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uuid.UUID) error); ok {
		r1 = returnFunc(userID, keyUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyService_ValidateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAPIKey'
type MockAPIKeyService_ValidateAPIKey_Call struct {
	*mock.Call
}

// ValidateAPIKey is a helper method to define mock.On call
//   - userID uint
//   - keyUUID uuid.UUID
func (_e *MockAPIKeyService_Expecter) ValidateAPIKey(userID interface{}, keyUUID interface{}) *MockAPIKeyService_ValidateAPIKey_Call {
	return &MockAPIKeyService_ValidateAPIKey_Call{Call: _e.mock.On("ValidateAPIKey", userID, keyUUID)}
}

func (_c *MockAPIKeyService_ValidateAPIKey_Call) Run(run func(userID uint, keyUUID uuid.UUID)) *MockAPIKeyService_ValidateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_ValidateAPIKey_Call) Return(aPIKey *models.APIKey, err error) *MockAPIKeyService_ValidateAPIKey_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyService_ValidateAPIKey_Call) RunAndReturn(run func(userID uint, keyUUID uuid.UUID) (*models.APIKey, error)) *MockAPIKeyService_ValidateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}
